//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractPU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public System.DateTime contractDate { get; set; }
        public Nullable<int> contragentId { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<int> educatorId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public Nullable<decimal> priceWithCredit { get; set; }
        public Nullable<decimal> totalWithCredit { get; set; }
        public Nullable<decimal> totalWithoutCredit { get; set; }
        public Nullable<decimal> priceWithoutCredit { get; set; }
        public decimal sumOfContract { get; set; }
        public decimal DDS { get; set; }
        public decimal deductionsForPU { get; set; }
        public decimal deductionsForDKPRPS { get; set; }
        public decimal remunerationFee { get; set; }
        public decimal materialCost { get; set; }
        public int contractNumber { get; set; }
    
        public virtual Contraget Contraget { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Educator Educator { get; set; }
    }
}
