//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractPU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PUEntitiesOne : DbContext
    {
        public PUEntitiesOne()
            : base("name=PUEntitiesOne")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Contraget> Contragets { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Educator> Educators { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int InsertArea(string areaName)
        {
            var areaNameParameter = areaName != null ?
                new ObjectParameter("areaName", areaName) :
                new ObjectParameter("areaName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertArea", areaNameParameter);
        }
    
        public virtual int DeleteArea(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteArea", idParameter);
        }
    }
}
